smarter build, push

diff --git a/doc b/doc
--- a/doc
+++ b/doc
@@ -128,7 +128,7 @@ esac
 use_services=0
 case "${1:-}" in
   version)
-    echo "1.3.1"
+    echo "1.4.0"
   ;;
   ps)
     docker-compose ps
@@ -165,7 +165,15 @@ case "${1:-}" in
 
     for service in $services; do
       (
-        docker-compose build --compress $service
+        while true; do
+          set +e
+            # 2>&1 redir is needed because "uses an image, skipping" goes to stderr
+            2>&1 docker-compose build --compress "$service" | tee /dev/stderr | grep "uses an image, skipping\|Successfully tagged" && break
+          set -e
+
+          echo "build retry"
+          sleep 1
+        done
       ) >&1 | sed -le "s#^#build $service: #;" &
       pids["$service"]=$!
     done
@@ -185,9 +193,18 @@ case "${1:-}" in
     for service in $services; do
       (
         while true; do
-          docker-compose build "$service" 2>&1 | grep "uses an image, skipping" && break
+          # the only way to get image nicely
+          # set +e required if no image is tagged
+          set +e
+            image="$(2>&1 docker-compose build --compress "$service" | grep "Successfully tagged" | cut -d' ' -f3-)"
+          set -e
 
-          docker push "$(docker-compose build "$service" | grep "Successfully tagged" | cut -d' ' -f3-)" && break
+          if [ "$image" = "" ]; then
+            echo "not tagged, not pushing"
+            break
+          fi
+
+          docker push "$image" && break
           sleep 1
         done
       ) 2>&1 | sed -le "s#^#push $service: #;" &
@@ -198,7 +215,7 @@ case "${1:-}" in
     do
       pid=${pids["$service"]}
       if ! wait $pid; then
-        echo "Building of $service failed"
+        echo "Pushing of $service failed"
       fi
     done
   ;;
